name: roptani_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State management
  flutter_riverpod: ^3.0.0
  riverpod: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & code quality
  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica.regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/coolvetica.italic.otf
          weight: 400
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic