// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwIuo2QJnQ4CjbdZKGyex0FpA_sT6MpuA',
    appId: '1:682675089378:web:7f9abd7597169227f5d3bb',
    messagingSenderId: '682675089378',
    projectId: 'cwt-starter-template',
    authDomain: 'cwt-starter-template.firebaseapp.com',
    storageBucket: 'cwt-starter-template.firebasestorage.app',
    measurementId: 'G-LYRP4TRSDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJNqbp7eASRcDoYZzRdwAQ_e22bQW3Ne4',
    appId: '1:682675089378:android:9d2ffd958d37e615f5d3bb',
    messagingSenderId: '682675089378',
    projectId: 'cwt-starter-template',
    storageBucket: 'cwt-starter-template.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5PFyV8Bt4uYFK0dDZhABPEjJqM9ifBCE',
    appId: '1:682675089378:ios:3e2c89a3d89c6759f5d3bb',
    messagingSenderId: '682675089378',
    projectId: 'cwt-starter-template',
    storageBucket: 'cwt-starter-template.firebasestorage.app',
    androidClientId: '682675089378-jttk67iffsimbo6t15cbr2uusbk0jllf.apps.googleusercontent.com',
    iosClientId: '682675089378-kq81i5hh18q0mf83mn7lo8651eikfbjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtStarterTemplate',
  );

}